version: 2.1.1
last_compiled: 2026-01-20 16:50:39

# ================================================
# Compiled with the following settings:
#
# To change these settings, run ~/agent-os/scripts/project-update.sh to re-compile your project with the new settings.
# ================================================
profile: 123jus-ui
claude_code_commands: false
use_claude_code_subagents: false
agent_os_commands: false
standards_as_claude_code_skills: false
